export { default as Main } from './Main.vue'
export { default as MainFeature } from './MainFeature.vue'
export { default as Hero } from './Hero.vue'
export { default as Features } from './Features.vue'
export { default as TabGrid } from './TabGrid.vue'
export { default as MainFeature2 } from './MainFeature2.vue'
export { default as Testimonial } from './Testimonial.vue'
export { default as DownloadApp } from './DownloadApp.vue'

export * from './type'